# conda env create --file environment.yml
name: missing_values
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pyjanitor
  - missingno
  - numpy
  - matplotlib=3.5.1
  - pandas
  - pyreadr
  - seaborn
  - session-info
  - upsetplot=0.6.1
  - python=3.9

